### ISSUE TITLE
Why compress jpg, png and gif?

### ISSUE THREAD

**Issue by buschtoens** [ember-cli-deploy/ember-cli-deploy-gzip#14]
I just saw that jpg, png and gif images are compressed by default. These formats already are compressed and it is unlikely that gzipping them will reduce the file size. In fact, it might even increase it and / or introduce a slight performance regression on the client-side due to the added (and unnecessary) CPU work.

If this is a mistake and not intended, I'll submit a PR to fix this - if wanted.

**Comment by lukemelia** [comment]
@buschtoens Excellent point. I agree with your analysis. We should change the defaults and a PR for this would be most welcome.
