### ISSUE TITLE
gzipped javascript files produce errors

### ISSUE THREAD

**Issue by gossi** [ember-cli-deploy/ember-cli-deploy-gzip#26]
I installed and `ember-cli-deploy-gzip` run a deploy, my assets are uploaded and they contain errors:

- Chrome: `Uncaught SyntaxError: Invalid or unexpected token`
- Firefox: `SyntaxError: illegal character`

Both at `vendor-***.js:1`

My config is here:
```js
	ENV.gzip = {
		ignorePattern: '**/{crossdomain.xml,robots.txt}'
	};
```

Without the ignorePattern, the browsers also weren't able to parse crossdomain.xml or rather robots.txt

**Comment by gossi** [comment]
Nevermind. Server-settings were incorrect.

**Comment by leondmello** [comment]
@gossi I'm facing the same error. Makes me think it has something to do with `nginx` and `gzip`
But I still cant get it to work. Add the configuration options [mentioned here](https://medium.com/@selvaganesh93/how-to-serve-webpack-gzipped-file-in-production-using-nginx-692eadbb9f1c) to set the correct `content-encoding` (gzip) response header value

**Comment by gossi** [comment]
It was 2.5 yrs ago - I can't remember.

**Comment by leondmello** [comment]
I was able to fix it by setting `keep=true`

**Comment by sankp** [comment]
Hello @leondmello how did you fixed this. I have recently converted my angular 2 project into lazy loaded modules. Works great and improved a lot in dev environment however for Prod we have been using compression of webpack and i am running into invalid token errors on gzip files.

**Comment by cah-sandip-bhoi** [comment]
> I was able to fix it by setting `keep=true`

Could you please elaborate more, where was this change done.

**Comment by leondmello** [comment]
In your `config/deploy.js` 
```js
ENV["gzip"] = {
      keep: true,
    };
```

**Comment by OZZlE** [comment]
What would be the equivalent in express.js? My webpack config:

    const path = require('path');
    const CompressionPlugin = require('compression-webpack-plugin');

    module.exports = {
      mode: 'production',
      context: path.join(__dirname, './'),
      entry: './app/app.jsx',
      output: {
        path: path.join(__dirname, 'public'),
        filename: 'bundle.js',
      },
      resolve: {
        extensions: ['.js', '.jsx'],
      },
      module: {
        rules: [
          {
            test: /\.jsx?$/,
            loader: 'jsx-loader',
            exclude: /node_modules/,
            include: path.join(__dirname, 'app'),
          },
          {
            test: /\.css$/i,
            use: ['style-loader', 'css-loader'],
          },
        ],
      },
      plugins: [
        new CompressionPlugin({
          filename: '[path].gz[query]',
          algorithm: 'gzip',
          test: /\.js$|\.css$|\.html$|\.eot?.+$|\.ttf?.+$|\.woff?.+$|\.svg?.+$/,
          threshold: 10240,
          minRatio: 0.8
        }),
      ]
    };

server.js:

    app.get("/", function(request, response) {
       response.sendFile(__dirname + '/app/index.html');
    });

And then inside index I just have:
 
    <script type="text/javascript" src="/bundle.js.gz"></script>

It even gets: Content-Type: application/gzip

**Comment by OZZlE** [comment]
This was my problem :) https://stackoverflow.com/a/63794100/846348
