### ISSUE TITLE
Issue with compressed files

### ISSUE THREAD

**Issue by chrism** [ember-cli-deploy/ember-cli-deploy-gzip#29]
Hi,

If I use `ember-cli-deploy` without gzip things work fine.

After installing `ember-cli-deploy-gzip` the assets now render from the server as strange characters.

For example, my application js file if I go to the URL displays this

```
‹������í}ÛvÛF²è»¿Á¬Ë�L‚Q˜Å#kì8ËñXv2{kky5&	`\$2Š^ÏóùÆó%§ª»q%HŒ$‹9Qb	è®nTUWUWõUŽC*…Q`›‘üÄ¢SÛ¥-Ùˆ;£j@,ÛS¯é„øþ3b?¢Aø^Û$‘í¹²r!Ó¥ïQ(+2]Lh Z$"ðRUEÙNølF]ˆª‘÷™ºò¥2]kkQ%R‚öÍÏ“OÔŒ4ŽÌÛÀói­ Sþø‘†gž;TVn®ˆSã›Îm[¡Kb'GÉ“öÏóŸßœ¼ýñ„c­ÑeD]«u3÷ÂÈçQäÏ€[×†GW3½…¬¸dACŸ˜Ô¯tY™SbÝÆ$!ü8¢VKæéGÎ(hZDÇ­Ž$¨´[ÑÜµ¼ý$ Q¸7ò¿Õßæú`[²Aµ8¶-Ò>‰£¹úž1’§ùÄ4©©¯Õ˜Ì¨lÈÔU?œË··míÊs IÚjßÂJ­–d©Å6¬ßò¢¹mwê@kyÁ}5dÒr_b¬Œò'
Ä) 
```
(I've just included the start to give an illustration the actual file is a lot longer).

I notice that if I look in the `/tmp/deploy-dist/assets` directory this matches how the file looks locally there.

Initially I thought it might be an issue with the server not supporting gzip, so I followed a tutorial online and now when I use a site to check for gzip support it says that GZIP is supported.

So now I'm at a loss as to how to fix this.

**Comment by achambers** [comment]
Hi @chrism. I suspect this is due to the fact that whatever mechanism that is serving your file is not adding the header to
Indicate that the content type of the file is gzipped. 

The reason it opens like that on the file system is also because it’s gzipped. 

Can you confirm for me what the content type header of the file returned from the server is?

Even better, are you able to provide me a url to the file I can look at myself?

**Comment by chrism** [comment]
Hi @achambers.

Sure, thanks so much for taking a look.

I've just deployed using gzip and an example file where this issue occurs is here:

http://wradio.orange.com/assets/orange-radio-webapp-ce90e9ac3f6cb5bb328239085f57e230.js

Without this plugin the files work fine.

All I am doing is using the `ember-cli-deploy-rsync` with details like this

```
    rsync: {
      host: myenv.hostname,
      dest: myenv.directory
      privateKey: myenv.privateKey,
      delete: false
    }
```

**Comment by achambers** [comment]
No probs @chrism.  We’ll get you moving shortly. I’m not at a laptop right now but I’ll take a closer look as soon as I can this evening and get back to you. 

Out of interest, what is serving your assets?

**Comment by chrism** [comment]
Thanks again @achambers it's a vanilla Apache install (if thats what you mean?).

**Comment by achambers** [comment]
@chrism So, as I mentioned above, your web server that's serving the assets is not setting the correct `content-encoding` header. In fact it's not setting one at all. This means that it's not telling the browser that the file is encoded with gzip.  You can see this here:

![image](https://user-images.githubusercontent.com/416724/46626670-e9ba4400-cb2f-11e8-8bc6-120ce5ae7c94.png)

What you need is for your server to be returning the `content-type: gzip` header for the assets that are gzipped. Like so:

![image](https://user-images.githubusercontent.com/416724/46626699-ffc80480-cb2f-11e8-9751-6398fe708703.png)

This should get you on your way. I'm going to close this issue now. If you have any further questions or believe this not to be the solution, feel free to re-open. But I believe this should be the info you need to get you moving in the right direction.

**Comment by chrism** [comment]
Once again thanks @achambers - completely understand it’s more on the server side than the deploy pipeline.

I’m going to look into how to get it to add that header and if, by some miracle, I can get it working will write up a blog post!

Thanks again for looking into it.

**Comment by chrism** [comment]
Even though this issue is closed I'm just following up in case someone else faces this issue themselves hosting an Ember app on Apache.

In the end it was due not just to the encoding but the 'double gzip' issue, where already gzipped files get compressed again.

For my particular use case it was only really the javascript files which I wanted to be gzipped as images were hosted elsewhere.

By adding to `.htaccess`

```
<FilesMatch "\.js$">
    Header set Content-Encoding gzip
    RewriteRule ^(.*)$ $1 [NS,E=no-gzip:1,E=dont-vary:1]
</FilesMatch>
```

it ensures that this doesn't happen to those files.

The other thing I did was use the `filePattern` config to only compress `.js` files in `deploy.js`.

```
    gzip: {
      filePattern: '**/*.js'
    }
```

Thanks again for your help @achambers I got there in the end :)

**Comment by achambers** [comment]
Great to hear you got there @chrism :)

Out of interest, when you mention “double gzip”, when was the second gzip happening?

**Comment by chrism** [comment]
I got the name from this description in the apache docs @achambers.
https://httpd.apache.org/docs/2.4/en/mod/mod_deflate.html#precompressed

Effectively `mod_deflate` automatically re-compresses when a request is made so you need to explicitly tell it to serve them without doing that.

Hope that makes more sense—this server config stuff is really not my thing, but didn't have much choice as I really wanted to get the vendor.js down to a more respectable size.
